minimum_prek_version = "0.3.9"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos.hooks]]
id = "check-case-conflict"

[[repos.hooks]]
id = "detect-private-key"

[[repos.hooks]]
id = "check-added-large-files"
args = ["--maxkb=1024"]

[[repos.hooks]]
id = "check-yaml"
args = ["--allow-multiple-documents"]

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "fix-byte-order-marker"

[[repos.hooks]]
id = "trailing-whitespace"
args = ["--markdown-linebreak-ext=md"]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.1"

[[repos.hooks]]
id = "gitleaks"
